### ISSUE TITLE
Ant-calib: TAPS_Energy_RelativeGains: Previous fit params broken

### ISSUE THREAD

**Issue by osteffen** [A2-Collaboration-dev/ant#44]
Loading previous fit parameters does not work. gives weird results.
"Use parameters from previous slice" seems has no effect?

**Comment by neiser** [comment]
The magic happens in the base class CalibType for calibration modules, [CalibType::StartSlice](https://github.com/A2-Collaboration-dev/ant/blob/master/src/calibration/modules/CalibType.cc#L79), but I can't spot an error there?!
